apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ./application-controller
- ./dex
- ./repo-server
- ./server
- ./config
- ./redis

images:
- name: argoproj/argocd
  newName: docker.io/yieldlab/argo-cd
  newTag: v1.0.1-yieldlab-backport-1684
- name: argoproj/argocd-ui
  newName: argoproj/argocd-ui
  newTag: v1.0.1
